=head1 NAME

synctl-fsck - Check and repair server content

=head1 SYNOPSIS

I<synctl fsck> [<options>...] [--server=<location> | <profile>]

=head1 DESCRIPTION

Check the specified server for errors and try to repair them. If some errors
cannot be fixed, the corrupted snapshots are marked and the command returns
1, otherwise it returns 0.
This operation can takes a long time.

=head1 OPTIONS

=over

=item -C <path>, --directory=<path>

Change the search path for the profile file. This options may be specified many
times to indicate many search directories. Several paths separated by ':' can
be specified in a single option.

=item -s <location>, --server=<location>

Indicate the location of the server to list. A location has the form
'(protocol)://(path)(path-extensions)'. If the protocol is 'file', it may be
omitted.

=item -v<level>, --verbose=<level>

Change the verbosity level. If specified with an argument, defines the new
level, from 0 (nothing) to 4 (debug). If specified without an argument,
increment the level by 1. The default level is 2 (warning).

=item --ssh-local=<command>

Use the specified command on the local side when accessing an ssh server.
Default is 'ssh'.

=item --ssh-remote=<command>

Use the specified command on the remote side when accessing an ssh server.
Default is 'synctl serve'.

=back

=cut
